blueprint:
  name: Warm/Koud Weer
  description: "Schakel een helper die gebruikt wordt in een andere automatisatie. 
    Deze helper geef weer of het warm of koud weer is. \n Als het koud weer is, zal 
    enkel de ♨️verwarming♨️ gebruikt worden en de koeling niet. \n Als het warm 
    weer is, zal enkel de ❄️koeling❄️ gebruikt worden en de verwarming niet."
  domain: automation
  input:
    # Ask user for a time input. it should always be '/' followed by a number.
    # This number is used to re-run the automation every X minutes. Default is 
    # set to 'every 10 minutes of every hour'. This way the automation can keep 
    # updating and can give accurate output if it is hot or cold
    input_trigger_frequency:
      name: "⏱️Trigger Frequentie⏱️"
      description:
        "Geef een tijdsinterval mee. Dit moet altijd starten met `'/'.` Het cijfer
        dat geeft het aantal minuten weer. Dit wil zeggen dat deze automatisatie 
        om de `X` aantal minuten zal worden uitgevoerd."
      default: "/10"
      selector:
        text:
    
    # Ask the user for a temperature. If the current ouside temperature is higher 
    # than the user input, the output will be "Warm". If the outside temperature 
    # is lower than the user input, the output will be "Koud"
    input_temperature:
      name: "🌡️Temperatuur Drempelwaarde🌡️"
      description: "Geef een drempelwaarde voor de temperatuur mee. \n Als de 
      buitentemperatuur BOVEN deze drempelwaarde ligt, zal het worden beschouwd 
      als 🔥`warm` weer. \n \n Als de buitentemperatuur ONDER deze drempelwaarde ligt, 
      zal het worden beschouwd als ❄️`koud` weer."
      default: 20
      selector:
        number:
          min: 4.0
          max: 75.0
          step: 0.5
          mode: box
          unit_of_measurement: "°C"

    # Ask the user for the correct helper that was made before making this automation
    # This helper is used in the other automation to descisde if it is hot or cold weather.
    input_helper:
      name: "🔧Helper🔧"
      description: "❗Maak eerst een helper aan die gebruikt kan worden voor het 
      weergeven als het warm of koud weer is. Dit doe je als volgt: `instellingen -> apparaten en diensten -> helpers -> 
      helper aanmaken -> schakelaar -> geef een passende naam in`❗"
      selector:
        entity:
          multiple: false

# Use the time input that the user gave to re-run this automation
trigger:
  platform: time_pattern
  id: temp_update
  minutes: !input input_trigger_frequency

variables:
  input_temperature_user: !input input_temperature
  input_helper_user: !input input_helper

condition: []

action:
  - variables:
      # Make a variable that reads the outside temperature from the weather integration.
      # This integration is pre installed on every Home Assistant
      current_temp: "{{ state_attr('weather.forecast_thuis', 'temperature') }}"
  - choose:
      # if the current temperature (outside) is higher than the number that the user gave,
      # the output will be "Warm" and the boolean switch will be turned off
      - conditions:
          - "{{ current_temp > input_temperature_user}}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input input_helper

      # if the current temperature (outside) is lower than the number that the user gave,
      # the output will be "Koud" and the boolean switch wiil be turned on
      - conditions:
          - "{{ current_temp <= input_temperature_user}}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input input_helper
